name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: nv-palladium

    steps:
    - uses: actions/checkout@v4

    - name: Verify Zig installation
      run: zig version

    - name: Build
      run: zig build

    - name: Run tests
      run: zig build test

    - name: Build release-safe
      run: zig build -Doptimize=ReleaseSafe